### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-VictoriaDiro#1]
Really cool job @VictoriaDiro !!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] We need an h1 tag instead of 3 divs
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Avoid using percentage units for margins or paddings.
- [ ] There are some weird scroll bars, let's remove them: Remember the header should always have a fixed position 
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Download the Adalab logo to a proper folder (although it is ok to use an absolute path we are going to use relative paths to a project file)
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed try to finish the styles.

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Hi, @VictoriaDiro:

I unchecked three checkboxes that need to be fixed. Go for it!

**Comment by VictoriaDiro** [comment]
Hi, @oneeyedman:

I check tasks and I fixed HTML text and improve my commit messages, but, my problem now it´s fixed header: I check code and don't found any problem. I try see my code in CodePen and work it fine, and I see in other computer and it's work too. I send you CodePen's link for review: https://codepen.io/VictoriaDiro/pen/bZxRKN

See you tomorrow!
